import os
from dotenv import load_dotenv
import json

load_dotenv()

TG_TOKEN = os.getenv('TG_TOKEN')
SIM_TOKEN = os.getenv('SIM_TOKEN')
OLD_SIM_TOKEN = os.getenv('OLD_SIM_TOKEN')

data = json.load(open('data.json'))

old_country = {'Russia': 0, 'Ukraine': 1, 'Kazakhstan': 2,
               'China': 3, 'Philippines': 4, 'Myanmar': 5,
               'Indonesia': 6, 'Malaysia': 7, 'Kenya': 8,
               'Tanzania': 9, 'Vietnam': 10, 'Kyrgyzstan': 11,
               'USA': 12, 'Israel': 13, 'Hong Kong': 14,
               'Poland': 15, 'England': 16, 'Madagascar': 17,
               'Congo': 18, 'Nigeria': 19, 'Macau': 20,
               'Egypt': 21, 'India': 22, 'Ireland': 23,
               'Cambodia': 24, 'Laos': 25, 'Haiti': 26,
               'Ivory Coast': 27, 'Gambia': 28, 'Serbia': 29,
               'South Africa': 31, 'Romania': 32, 'Colombia': 33,
               'Estonia': 34, 'Azerbaijan': 35, 'Canada': 36,
               'Morocco': 37, 'Ghana': 38, 'Argentina': 39,
               'Uzbekistan': 40, 'Cameroon': 41, 'Chad': 42,
               'Germany': 43, 'Lithuania': 44, 'Croatia': 45,
               'Sweden': 46, 'Netherlands': 48, 'Latvia': 49,
               'Austria': 50, 'Belarus': 51, 'Thailand': 52,
               'Saudi Arabia': 53, 'Mexico': 54, 'Taiwan': 55,
               'Spain': 56, 'Algeria': 58, 'Slovenia': 59,
               'Bangladesh': 60, 'Senegal': 61, 'Turkey': 62,
               'Czechia': 63, 'Sri Lanka': 64, 'Peru': 65,
               'Pakistan': 66, 'New Zealand': 67, 'Guinea': 68,
               'Venezuela': 70, 'Ethiopia': 71, 'Mongolia': 72,
               'Brazil': 73, 'Afghanistan': 74, 'Uganda': 75,
               'Angola': 76, 'Cyprus': 77, 'France': 78,
               'Papua New Guinea': 79, 'Mozambique': 80, 'Nepal': 81,
               'Belgium': 82, 'Bulgaria': 83, 'Hungary': 84,
               'Moldova': 85, 'Italy': 86, 'Paraguay': 87,
               'Honduras': 88, 'Tunisia': 89, 'Nicaragua': 90,
               'East Timor': 91, 'Bolivia': 92, 'Costa Rica': 93,
               'Guatemala': 94, 'Zimbabwe': 96, 'Puertorico': 97,
               'Togo': 99, 'Kuwait': 100, 'Salvador': 101,
               'Jamaica': 103, 'Trinidad and Tobago': 104, 'Ecuador': 105,
               'Swaziland': 106, 'Oman': 107, 'Bosnia and Herzegovina': 108,
               'Dominican Republic': 109, 'Panama': 112, 'Mauritania': 114,
               'Sierra Leone': 115, 'Jordan': 116, 'Portugal': 117,
               'Barbados': 118, 'Burundi': 119, 'Benin': 120,
               'Botswana': 123, 'Georgia': 128, 'Greece': 129,
               'Guinea - Bissau': 130, 'Guyana': 131, 'Saint Kitts and Nevis': 134,
               'Liberia': 135, 'Lesotho': 136, 'Malawi': 137,
               'Namibia': 138, 'Rwanda': 140, 'Slovakia': 141,
               'Suriname': 142, 'Tajikistan': 143, 'Bahrain': 145,
               'Reunion': 146, 'Zambia': 147, 'Armenia': 148,
               'Burkina Faso': 152, 'Gabon': 154, 'Albania': 155,
               'Uruguay': 156, 'Mauritius': 157, 'Bhutan': 158,
               'Maldives': 159, 'Guadeloupe': 160, 'Turkmenistan': 161,
               'French Guiana': 162, 'Finland': 163, 'Saint Lucia': 164,
               'Luxembourg': 165, 'Saint Vincent and the Grenadines': 166, 'Equatorial Guinea': 167,
               'Djibouti': 168, 'Antigua and Barbuda': 169, 'Cayman Islands': 170,
               'Montenegro': 171, 'Switzerland': 173, 'Norway': 174,
               'Australia': 175, 'Eritrea': 176, 'Sao Tome and Principe': 178,
               'Aruba': 179, 'Montserrat': 180, 'Anguilla': 181,
               'Japan': 182, 'North Macedonia': 183, 'Republic of Seychelles': 184,
               'New Caledonia': 185, 'Cape Verde': 186}

available_service = {'1688': 'hn', '1xbet': 'wj', '32red': 'qi', '888casino': 'll',
                     '99app': 'ki', 'adidas': 'an', 'agroinform': 'qu', 'airbnb': 'uk',
                     'airtel': 'zl', 'airtel': 'wf', 'aitu': 'jj', 'alfa': 'bt',
                     'algida': 'lp', 'alibaba': 'ab', 'aliexpress': 'hx', 'aliexpress': 'al',
                     'alipay': 'hw', 'amasia': 'yo', 'amazon': 'am', 'aol': 'pm',
                     'apple': 'wx', 'astropay ': 'sp', 'auchan': 'st', 'avito': 'av',
                     'avon': 'ff', 'b4ucabs': 'bu', 'baidu': 'li', 'banqi': 'vc',
                     'bigolive': 'bl', 'billmill': 'ri', 'bisu': 'el', 'bitaqaty': 'pt',
                     'bitclout': 'lt', 'blablacar': 'ua', 'blizzard': 'bz', 'blued': 'qn',
                     'bolt': 'tx', 'brand20ua': 'vo', 'burgerking': 'ip', 'bykea': 'iu',
                     'cafebazaar': 'uo', 'caixa': 'my', 'careem': 'ls', 'carousell': 'gj',
                     'cdkeys': 'pq', 'citaprevia': 'si', 'citymobil': 'yf', 'cliqq': 'fe',
                     'clubhouse': 'et', 'cmtcuzdan': 'ql', 'coinbase': 're', 'coinfield': 'vw',
                     'craigslist': 'wc', 'cryptocom': 'ti', 'dbrua': 'tj', 'deliveroo': 'zk',
                     'delivery': 'dt', 'dent': 'zz', 'dhani': 'os', 'didi': 'xk',
                     'digikala': 'zv', 'discord': 'ds', 'disneyhotstar': 'ud', 'divar': 'dw',
                     'dodopizza': 'sd', 'dominospizza': 'dz', 'dostavista': 'sv', 'douyu': 'ak',
                     'dream11': 've', 'drom': 'hz', 'drugvokrug': 'we', 'easypay': 'rz',
                     'ebay': 'dh', 'ebikegewinnspiel': 'le', 'eneba': 'uf', 'ezbuy': 'db',
                     'faberlic': 'rm', 'facebook': 'fb', 'fiqsy': 'ug', 'fiverr': 'cn',
                     'foodpanda': 'nz', 'foody': 'kw', 'freecharge ': 'tp', 'gamearena': 'wn',
                     'gamekit': 'pa', 'gamer': 'ed', 'getir': 'ul', 'gett': 'gt',
                     'gg': 'qe', 'gittigidiyor': 'nk', 'global24': 'iz', 'globaltel': 'gl',
                     'globus': 'hm', 'glovo': 'aq', 'google': 'go', 'grabtaxi': 'jg',
                     'grindr': 'yw', 'hamrahaval': 'rp', 'happn': 'df', 'haraj': 'au',
                     'hepsiburadacom': 'gx', 'hezzl': 'ss', 'hily': 'rt', 'hopi': 'jl',
                     'hqtrivia': 'kp', 'humblebundle': 'un', 'humta': 'gv', 'huya': 'pp',
                     'icq': 'iq', 'icrypex': 'cx', 'ifood': 'pd', 'immowelt': 'ib',
                     'imo': 'im', 'inboxlv': 'iv', 'indriver': 'rl', 'ininal': 'hy',
                     'instagram': 'ig', 'iqos': 'il', 'ivi': 'jc', 'jd': 'za',
                     'jkf': 'hr', 'justdating': 'pu', 'justdial ': 'dl', 'kakaotalk': 'kt',
                     'karusel': 'de', 'keybase': 'bf', 'kotak811': 'rv', 'kucoinplay': 'sq',
                     'kufarby': 'kb', 'kvartplata': 'yb', 'kwai': 'vp', 'lazada': 'dl',
                     'lenta': 'rd', 'line': 'me', 'linkedin': 'tn', 'livescore': 'eu',
                     'magnit': 'mg', 'magnolia': 'up', 'mailru': 'ma', 'mamba': 'fd',
                     'mcdonalds': 'ry', 'mega': 'qr', 'mercado': 'cq', 'michat': 'mc',
                     'microsoft': 'mm', 'miloan': 'ey', 'miratorg': 'op', 'mobile01': 'wk',
                     'momo': 'hc', 'monese': 'py', 'monobank': 'ji', 'mosru': 'ce',
                     'mrgreen': 'lw', 'mtscashback': 'da', 'myfishka': 'qa', 'myglo': 'ae',
                     'mylove': 'fy', 'mymusictaste': 'mu', 'mzadqatar': 'jm', 'nana': 'na',
                     'naver': 'nv', 'ncsoft': 'sw', 'netflix': 'nf', 'nhseven ': 'h7',
                     'nifty': 'px', 'nike': 'ew', 'nrjmusicawards': 'pg', 'nttgame': 'zy',
                     'odnoklassniki': 'ok', 'offerup': 'zm', 'offgamers': 'uz', 'okta': 'lr',
                     'olacabs': 'ly', 'olx': 'sn', 'onlinerby': 'ob', 'oriflame': 'qh',
                     'other': 'ot', 'ozon': 'sg', 'paddypower': 'cw', 'pairs': 'dk',
                     'papara': 'zr', 'paxful': 'dn', 'payberry': 'qb', 'paycell': 'xz',
                     'paypal': 'ts', 'paysend': 'tr', 'paytm': 'ge', 'peoplecom': 'pe',
                     'perekrestok': 'pl', 'pgbonus': 'fx', 'picpay': 'ev', 'pof': 'pf',
                     'pokec': 'pk', 'potato': 'fj', 'powerkredite': 'dx', 'prajmeriz2020': 'qc',
                     'premiumone': 'po', 'prom': 'cm', 'protonmail': 'dp', 'protp ': 'ra',
                     'pureplatfrom': 'lk', 'pyaterochka': 'bd', 'pyromusic': 'ny', 'q12trivia': 'vf',
                     'qiwiwallet': 'qw', 'quipp': 'cc', 'rambler': 'tc', 'rediffmail': 'co',
                     'rosakhutor': 'qm', 'rsa': 'cy', 'rutube': 'ui', 'samokat': 'jr',
                     'seosprint': 'vv', 'sheerid': 'rx', 'zalo': 'mj', 'zoho': 'zh',
                     'shopee': 'ka', 'sikayetvar': 'fs', 'skout': 'wg', 'snapchat': 'fu',
                     'snappfood': 'ph', 'sneakersnstuff': 'sf', 'socios': 'ia', 'sportmaster': 'yk',
                     'spothit': 'cd', 'ssoidnet': 'la', 'steam': 'mt', 'surveytime': 'gd',
                     'swvl': 'tq', 'taksheel': 'ei', 'tango': 'xr', 'tantan': 'ta',
                     'taobao': 'qd', 'telegram': 'tg', 'tencentqq': 'qq', 'ticketmaster': 'gp',
                     'tiktok': 'lf', 'tinder': 'oi', 'tosla': 'nr', 'touchance': 'fm',
                     'trendyol': 'pr', 'truecaller': 'tl', 'twitch': 'hb', 'twitter': 'tw',
                     'uber': 'ub', 'ukrnet': 'hu', 'vernyj': 'nb', 'viber': 'vi',
                     'vitajekspress': 'bj', 'vkontakte': 'vk', 'wechat': 'wb', 'weibo': 'kf',
                     'weststein': 'th', 'whatsapp': 'wa', 'wildberries': 'uu', 'wingmoney': 'jb',
                     'wish': 'xv', 'wmaraci': 'xl', 'wolt': 'rr', 'yaay': 'vn',
                     'yahoo': 'mb', 'yalla': 'yl', 'yandex': 'ya', 'yemeksepeti': 'yi',
                     'youla': 'ym', 'youstar': 'gb'}
